# training parameters

batch_size: 512
no_epochs: 300
device: cpu

lr: 1e-5

manual_seed: 0

save_dir: ../runs # for output

# validations parameters (should align with/be infered from data config)
regular_val_set_provided: true
val_trajectory_length: 101 # needs to be alined with data_set parameters
x_start: [1, 0] # must be such that casted to 1-dimensional array/tensor
t_start: 0
t_end: 1
no_bridges: 10 # could/should be linked to subsampling rate 
stepsize: 1e-3

irregular_val_set_provided: false
