# training parameters
batch_size: 5
no_epochs: 20 #1041
device: cpu

lr: 1e-5

manual_seed: 0

save_dir: ../runs_aemet # for output

# validations parameters (should align with/be infered from data config)
regular_val_set_provided: true
val_trajectory_length: 365
x_start: [1] # must be such that casted to 1-dimensional array/tensor
t_start: 0
t_end: 1
no_bridges: 14 # could/should be linked to subsampling rate 
stepsize: 0.0027472527472527475

irregular_val_set_provided: false
# TODO
