# training parameters

batch_size: 512
no_epochs: 50
device: cpu

lr: 1e-5

manual_seed: 2

save_dir: ../runs_stock1d # for output

# validations parameters (should align with/be infered from data config)
regular_val_set_provided: true
val_trajectory_length: 101
x_start: [1] # must be such that casted to 1-dimensional array/tensor
t_start: 0
t_end: 1
no_bridges: 10 # could/should be linked to subsampling rate 
stepsize: 1e-3

# validation start distribution
mixture:
  enabled: false
  p_bm1: 0.5
  bm1:
    S0: 1.0
  bm2:
    S0: 0.0

irregular_val_set_provided: false
# TODO
